import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
} from 'react-native';

const PrivacyPolicy = ({ navigation }) => {
  const handleBackClick = () => {
    navigation.goBack();
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={handleBackClick}>
          <Text style={styles.backButtonText}>← Back</Text>
        </TouchableOpacity>
      </View>

      <ScrollView 
        style={styles.scrollView}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={true}
      >
        <View style={styles.card}>
          <Text style={styles.mainTitle}>PRIVACY POLICY</Text>

          <Text style={styles.paragraph}>Effective date: 2025-06-26</Text>

          <Text style={styles.paragraph}>
            1. <Text style={styles.bold}>Introduction</Text>
          </Text>

          <Text style={styles.paragraph}>
            Welcome to <Text style={styles.bold}>Hotel Virat</Text>.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Hotel Virat</Text> ("us", "we", or "our") operates{' '}
            <Text style={styles.bold}>http://192.168.1.24:9000</Text> (hereinafter referred to as{' '}
            <Text style={styles.bold}>"Service"</Text>).
          </Text>

          <Text style={styles.paragraph}>
            Our Privacy Policy governs your visit to{' '}
            <Text style={styles.bold}>http://192.168.1.24:9000</Text>, and explains how we collect,
            safeguard and disclose information that results from your use of our Service.
          </Text>

          <Text style={styles.paragraph}>
            We use your data to provide and improve Service. By using Service, you agree to the
            collection and use of information in accordance with this policy. Unless otherwise
            defined in this Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions.
          </Text>

          <Text style={styles.paragraph}>
            Our Terms and Conditions (<Text style={styles.bold}>"Terms"</Text>) govern all use of
            our Service and together with the Privacy Policy constitutes your agreement with us (
            <Text style={styles.bold}>"agreement"</Text>).
          </Text>

          <Text style={styles.paragraph}>
            2. <Text style={styles.bold}>Definitions</Text>
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>SERVICE</Text> means the http://192.168.1.24:9000 website
            operated by Hotel Virat.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>PERSONAL DATA</Text> means data about a living individual who
            can be identified from those data (or from those and other information either in our
            possession or likely to come into our possession).
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>USAGE DATA</Text> is data collected automatically either
            generated by the use of Service or from Service infrastructure itself (for example, the
            duration of a page visit).
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>COOKIES</Text> are small files stored on your device (computer
            or mobile device).
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA CONTROLLER</Text> means a natural or legal person who
            (either alone or jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be, processed. For the
            purpose of this Privacy Policy, we are a Data Controller of your data.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA PROCESSORS (OR SERVICE PROVIDERS)</Text> means any
            natural or legal person who processes the data on behalf of the Data Controller. We may
            use the services of various Service Providers in order to process your data more
            effectively.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>DATA SUBJECT</Text> is any living individual who is the
            subject of Personal Data.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>THE USER</Text> is the individual using our Service. The User
            corresponds to the Data Subject, who is the subject of Personal Data.
          </Text>

          <Text style={styles.paragraph}>
            3. <Text style={styles.bold}>Information Collection and Use</Text>
          </Text>

          <Text style={styles.paragraph}>
            We collect several different types of information for various purposes to provide and
            improve our Service to you.
          </Text>

          <Text style={styles.paragraph}>
            4. <Text style={styles.bold}>Types of Data Collected</Text>
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Personal Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            While using our Service, we may ask you to provide us with certain personally
            identifiable information that can be used to contact or identify you (
            <Text style={styles.bold}>"Personal Data"</Text>). Personally identifiable information
            may include, but is not limited to:
          </Text>

          <Text style={styles.paragraph}>0.1. Email address</Text>

          <Text style={styles.paragraph}>0.2. First name and last name</Text>

          <Text style={styles.paragraph}>0.3. Phone number</Text>

          <Text style={styles.paragraph}>
            0.4. Address, Country, State, Province, ZIP/Postal code, City
          </Text>

          <Text style={styles.paragraph}>0.5. Cookies and Usage Data</Text>

          <Text style={styles.paragraph}>
            We may use your Personal Data to contact you with newsletters, marketing or promotional
            materials and other information that may be of interest to you. You may opt out of
            receiving any, or all, of these communications from us by following the unsubscribe
            link.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Usage Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may also collect information that your browser sends whenever you visit our Service
            or when you access Service by or through any device (
            <Text style={styles.bold}>"Usage Data"</Text>).
          </Text>

          <Text style={styles.paragraph}>
            This Usage Data may include information such as your computer's Internet Protocol
            address (e.g. IP address), browser type, browser version, the pages of our Service that
            you visit, the time and date of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </Text>

          <Text style={styles.paragraph}>
            When you access Service with a device, this Usage Data may include information such as
            the type of device you use, your device unique ID, the IP address of your device, your
            device operating system, the type of Internet browser you use, unique device identifiers
            and other diagnostic data.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Tracking Cookies Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            We use cookies and similar tracking technologies to track the activity on our Service
            and we hold certain information.
          </Text>

          <Text style={styles.paragraph}>
            Cookies are files with a small amount of data which may include an anonymous unique
            identifier. Cookies are sent to your browser from a website and stored on your device.
            Other tracking technologies are also used such as beacons, tags and scripts to collect
            and track information and to improve and analyze our Service.
          </Text>

          <Text style={styles.paragraph}>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is
            being sent. However, if you do not accept cookies, you may not be able to use some
            portions of our Service.
          </Text>

          <Text style={styles.paragraph}>Examples of Cookies we use:</Text>

          <Text style={styles.paragraph}>
            0.1. <Text style={styles.bold}>Session Cookies:</Text> We use Session Cookies to operate
            our Service.
          </Text>

          <Text style={styles.paragraph}>
            0.2. <Text style={styles.bold}>Preference Cookies:</Text> We use Preference Cookies to
            remember your preferences and various settings.
          </Text>

          <Text style={styles.paragraph}>
            0.3. <Text style={styles.bold}>Security Cookies:</Text> We use Security Cookies for
            security purposes.
          </Text>

          <Text style={styles.paragraph}>
            0.4. <Text style={styles.bold}>Advertising Cookies:</Text> Advertising Cookies are used
            to serve you with advertisements that may be relevant to you and your interests.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Other Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            While using our Service, we may also collect the following information: sex, age, date
            of birth, place of birth, passport details, citizenship, registration at place of
            residence and actual address, telephone number (work, mobile), details of documents on
            education, qualification, professional training, employment agreements, information on
            bonuses and compensation, information on marital status, family members, social security
            (or other taxpayer identification) number, office location and other data.
          </Text>

          <Text style={styles.paragraph}>
            5. <Text style={styles.bold}>Use of Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            Hotel Virat uses the collected data for various purposes:
          </Text>

          <Text style={styles.paragraph}>0.1. to provide and maintain our Service;</Text>

          <Text style={styles.paragraph}>0.2. to notify you about changes to our Service;</Text>

          <Text style={styles.paragraph}>
            0.3. to allow you to participate in interactive features of our Service when you choose
            to do so;
          </Text>

          <Text style={styles.paragraph}>0.4. to provide customer support;</Text>

          <Text style={styles.paragraph}>
            0.5. to gather analysis or valuable information so that we can improve our Service;
          </Text>

          <Text style={styles.paragraph}>0.6. to monitor the usage of our Service;</Text>

          <Text style={styles.paragraph}>
            0.7. to detect, prevent and address technical issues;
          </Text>

          <Text style={styles.paragraph}>
            0.8. to fulfil any other purpose for which you provide it;
          </Text>

          <Text style={styles.paragraph}>
            0.9. to carry out our obligations and enforce our rights arising from any contracts
            entered into between you and us, including for billing and collection;
          </Text>

          <Text style={styles.paragraph}>
            0.10. to provide you with notices about your account and/or subscription, including
            expiration and renewal notices, email-instructions, etc.;
          </Text>

          <Text style={styles.paragraph}>
            0.11. to provide you with news, special offers and general information about other
            goods, services and events which we offer that are similar to those that you have
            already purchased or enquired about unless you have opted not to receive such
            information;
          </Text>

          <Text style={styles.paragraph}>
            0.12. in any other way we may describe when you provide the information;
          </Text>

          <Text style={styles.paragraph}>0.13. for any other purpose with your consent.</Text>

          <Text style={styles.paragraph}>
            6. <Text style={styles.bold}>Retention of Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            We will retain your Personal Data only for as long as is necessary for the purposes set
            out in this Privacy Policy. We will retain and use your Personal Data to the extent
            necessary to comply with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes, and enforce our
            legal agreements and policies.
          </Text>

          <Text style={styles.paragraph}>
            We will also retain Usage Data for internal analysis purposes. Usage Data is generally
            retained for a shorter period, except when this data is used to strengthen the security
            or to improve the functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </Text>

          <Text style={styles.paragraph}>
            7. <Text style={styles.bold}>Transfer of Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            Your information, including Personal Data, may be transferred to – and maintained on –
            computers located outside of your state, province, country or other governmental
            jurisdiction where the data protection laws may differ from those of your jurisdiction.
          </Text>

          <Text style={styles.paragraph}>
            If you are located outside India and choose to provide information to us, please note
            that we transfer the data, including Personal Data, to India and process it there.
          </Text>

          <Text style={styles.paragraph}>
            Your consent to this Privacy Policy followed by your submission of such information
            represents your agreement to that transfer.
          </Text>

          <Text style={styles.paragraph}>
            Hotel Virat will take all the steps reasonably necessary to ensure that your data is
            treated securely and in accordance with this Privacy Policy and no transfer of your
            Personal Data will take place to an organisation or a country unless there are adequate
            controls in place including the security of your data and other personal information.
          </Text>

          <Text style={styles.paragraph}>
            8. <Text style={styles.bold}>Disclosure of Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may disclose personal information that we collect, or you provide:
          </Text>

          <Text style={styles.paragraph}>
            0.1. <Text style={styles.bold}>Business Transaction.</Text>
          </Text>

          <Text style={styles.paragraph}>
            If we or our subsidiaries are involved in a merger, acquisition or asset sale, your
            Personal Data may be transferred.
          </Text>

          <Text style={styles.paragraph}>
            0.2. <Text style={styles.bold}>Other cases. We may disclose your information also:</Text>
          </Text>

          <Text style={styles.paragraph}>0.2.1. to our subsidiaries and affiliates;</Text>

          <Text style={styles.paragraph}>
            0.2.2. to contractors, service providers, and other third parties we use to support our
            business;
          </Text>

          <Text style={styles.paragraph}>0.2.3. to fulfill the purpose for which you provide it;</Text>

          <Text style={styles.paragraph}>
            0.2.4. for the purpose of including your company's logo on our website;
          </Text>

          <Text style={styles.paragraph}>
            0.2.5. for any other purpose disclosed by us when you provide the information;
          </Text>

          <Text style={styles.paragraph}>0.2.6. with your consent in any other cases;</Text>

          <Text style={styles.paragraph}>
            0.2.7. if we believe disclosure is necessary or appropriate to protect the rights,
            property, or safety of the Company, our customers, or others.
          </Text>

          <Text style={styles.paragraph}>
            9. <Text style={styles.bold}>Security of Data</Text>
          </Text>

          <Text style={styles.paragraph}>
            The security of your data is important to us but remember that no method of transmission
            over the Internet or method of electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your Personal Data, we cannot guarantee its
            absolute security.
          </Text>

          <Text style={styles.paragraph}>
            10.{' '}
            <Text style={styles.bold}>
              Your Data Protection Rights Under General Data Protection Regulation (GDPR)
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            If you are a resident of the European Union (EU) and European Economic Area (EEA), you
            have certain data protection rights, covered by GDPR.
          </Text>

          <Text style={styles.paragraph}>
            We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use
            of your Personal Data.
          </Text>

          <Text style={styles.paragraph}>
            If you wish to be informed what Personal Data we hold about you and if you want it to be
            removed from our systems, please email us at{' '}
            <Text style={styles.bold}>infohotelvirat@gmail.com</Text>.
          </Text>

          <Text style={styles.paragraph}>
            In certain circumstances, you have the following data protection rights:
          </Text>

          <Text style={styles.paragraph}>
            0.1. the right to access, update or to delete the information we have on you;
          </Text>

          <Text style={styles.paragraph}>
            0.2. the right of rectification. You have the right to have your information rectified
            if that information is inaccurate or incomplete;
          </Text>

          <Text style={styles.paragraph}>
            0.3. the right to object. You have the right to object to our processing of your
            Personal Data;
          </Text>

          <Text style={styles.paragraph}>
            0.4. the right of restriction. You have the right to request that we restrict the
            processing of your personal information;
          </Text>

          <Text style={styles.paragraph}>
            0.5. the right to data portability. You have the right to be provided with a copy of
            your Personal Data in a structured, machine-readable and commonly used format;
          </Text>

          <Text style={styles.paragraph}>
            0.6. the right to withdraw consent. You also have the right to withdraw your consent at
            any time where we rely on your consent to process your personal information;
          </Text>

          <Text style={styles.paragraph}>
            Please note that we may ask you to verify your identity before responding to such
            requests. Please note, we may not able to provide Service without some necessary data.
          </Text>

          <Text style={styles.paragraph}>
            You have the right to complain to a Data Protection Authority about our collection and
            use of your Personal Data. For more information, please contact your local data
            protection authority in the European Economic Area (EEA).
          </Text>

          <Text style={styles.paragraph}>
            11.{' '}
            <Text style={styles.bold}>
              Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            CalOPPA is the first state law in the nation to require commercial websites and online
            services to post a privacy policy. The law's reach stretches well beyond California to
            require a person or company in the United States (and conceivable the world) that
            operates websites collecting personally identifiable information from California
            consumers to post a conspicuous privacy policy on its website stating exactly the
            information being collected and those individuals with whom it is being shared, and to
            comply with this policy.
          </Text>

          <Text style={styles.paragraph}>According to CalOPPA we agree to the following:</Text>

          <Text style={styles.paragraph}>0.1. users can visit our site anonymously;</Text>

          <Text style={styles.paragraph}>
            0.2. our Privacy Policy link includes the word "Privacy", and can easily be found on the
            home page of our website;
          </Text>

          <Text style={styles.paragraph}>
            0.3. users will be notified of any privacy policy changes on our Privacy Policy Page;
          </Text>

          <Text style={styles.paragraph}>
            0.4. users are able to change their personal information by emailing us at{' '}
            <Text style={styles.bold}>infohotelvirat@gmail.com</Text>.
          </Text>

          <Text style={styles.paragraph}>Our Policy on "Do Not Track" Signals:</Text>

          <Text style={styles.paragraph}>
            We honor Do Not Track signals and do not track, plant cookies, or use advertising when a
            Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in
            your web browser to inform websites that you do not want to be tracked.
          </Text>

          <Text style={styles.paragraph}>
            You can enable or disable Do Not Track by visiting the Preferences or Settings page of
            your web browser.
          </Text>

          <Text style={styles.paragraph}>
            12.{' '}
            <Text style={styles.bold}>
              Your Data Protection Rights under the California Consumer Privacy Act (CCPA)
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            If you are a California resident, you are entitled to learn what data we collect about
            you, ask to delete your data and not to sell (share) it. To exercise your data
            protection rights, you can make certain requests and ask us:
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>
              0.1. What personal information we have about you. If you make this request, we will
              return to you:
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            0.0.1. The categories of personal information we have collected about you.
          </Text>

          <Text style={styles.paragraph}>
            0.0.2. The categories of sources from which we collect your personal information.
          </Text>

          <Text style={styles.paragraph}>
            0.0.3. The business or commercial purpose for collecting or selling your personal
            information.
          </Text>

          <Text style={styles.paragraph}>
            0.0.4. The categories of third parties with whom we share personal information.
          </Text>

          <Text style={styles.paragraph}>
            0.0.5. The specific pieces of personal information we have collected about you.
          </Text>

          <Text style={styles.paragraph}>
            0.0.6. A list of categories of personal information that we have sold, along with the
            category of any other company we sold it to. If we have not sold your personal
            information, we will inform you of that fact.
          </Text>

          <Text style={styles.paragraph}>
            0.0.7. A list of categories of personal information that we have disclosed for a
            business purpose, along with the category of any other company we shared it with.
          </Text>

          <Text style={styles.paragraph}>
            Please note, you are entitled to ask us to provide you with this information up to two
            times in a rolling twelve-month period. When you make this request, the information
            provided may be limited to the personal information we collected about you in the
            previous 12 months.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>
              0.2. To delete your personal information. If you make this request, we will delete the
              personal information we hold about you as of the date of your request from our records
              and direct any service providers to do the same. In some cases, deletion may be
              accomplished through de-identification of the information. If you choose to delete
              your personal information, you may not be able to use certain functions that require
              your personal information to operate.
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>
              0.3. To stop selling your personal information. We don't sell or rent your personal
              information to any third parties for any purpose. We do not sell your personal
              information for monetary consideration. However, under some circumstances, a transfer
              of personal information to a third party, or within our family of companies, without
              monetary consideration may be considered a "sale" under California law. You are the
              only owner of your Personal Data and can request disclosure or deletion at any time.
            </Text>
          </Text>

          <Text style={styles.paragraph}>
            If you submit a request to stop selling your personal information, we will stop making
            such transfers.
          </Text>

          <Text style={styles.paragraph}>
            Please note, if you ask us to delete or stop selling your data, it may impact your
            experience with us, and you may not be able to participate in certain programs or
            membership services which require the usage of your personal information to function.
            But in no circumstances, we will discriminate against you for exercising your rights.
          </Text>

          <Text style={styles.paragraph}>
            To exercise your California data protection rights described above, please send your
            request(s) by email: <Text style={styles.bold}>infohotelvirat@gmail.com</Text>.
          </Text>

          <Text style={styles.paragraph}>
            Your data protection rights, described above, are covered by the CCPA, short for the
            California Consumer Privacy Act. To find out more, visit the official California
            Legislative Information website. The CCPA took effect on 01/01/2020.
          </Text>

          <Text style={styles.paragraph}>
            13. <Text style={styles.bold}>Service Providers</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may employ third party companies and individuals to facilitate our Service (
            <Text style={styles.bold}>"Service Providers"</Text>), provide Service on our behalf,
            perform Service-related services or assist us in analysing how our Service is used.
          </Text>

          <Text style={styles.paragraph}>
            These third parties have access to your Personal Data only to perform these tasks on our
            behalf and are obligated not to disclose or use it for any other purpose.
          </Text>

          <Text style={styles.paragraph}>
            14. <Text style={styles.bold}>Analytics</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may use third-party Service Providers to monitor and analyze the use of our Service.
          </Text>

          <Text style={styles.paragraph}>
            15. <Text style={styles.bold}>CI/CD tools</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may use third-party Service Providers to automate the development process of our
            Service.
          </Text>

          <Text style={styles.paragraph}>
            16. <Text style={styles.bold}>Behavioral Remarketing</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may use remarketing services to advertise on third party websites to you after you
            visited our Service. We and our third-party vendors use cookies to inform, optimise and
            serve ads based on your past visits to our Service.
          </Text>

          <Text style={styles.paragraph}>
            17. <Text style={styles.bold}>Payments</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may provide paid products and/or services within Service. In that case, we use
            third-party services for payment processing (e.g. payment processors).
          </Text>

          <Text style={styles.paragraph}>
            We will not store or collect your payment card details. That information is provided
            directly to our third-party payment processors whose use of your personal information is
            governed by their Privacy Policy. These payment processors adhere to the standards set
            by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of
            brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help
            ensure the secure handling of payment information.
          </Text>

          <Text style={styles.paragraph}>
            18. <Text style={styles.bold}>Links to Other Sites</Text>
          </Text>

          <Text style={styles.paragraph}>
            Our Service may contain links to other sites that are not operated by us. If you click a
            third party link, you will be directed to that third party's site. We strongly advise
            you to review the Privacy Policy of every site you visit.
          </Text>

          <Text style={styles.paragraph}>
            We have no control over and assume no responsibility for the content, privacy policies
            or practices of any third party sites or services.
          </Text>

          <Text style={styles.paragraph}>
            19. <Text style={styles.bold}>Children's Privacy</Text>
          </Text>

          <Text style={styles.paragraph}>
            Our Services are not intended for use by children under the age of 18 (
            <Text style={styles.bold}>"Child"</Text> or <Text style={styles.bold}>"Children"</Text>
            ).
          </Text>

          <Text style={styles.paragraph}>
            We do not knowingly collect personally identifiable information from Children under 18.
            If you become aware that a Child has provided us with Personal Data, please contact us.
            If we become aware that we have collected Personal Data from Children without
            verification of parental consent, we take steps to remove that information from our
            servers.
          </Text>

          <Text style={styles.paragraph}>
            20. <Text style={styles.bold}>Changes to This Privacy Policy</Text>
          </Text>

          <Text style={styles.paragraph}>
            We may update our Privacy Policy from time to time. We will notify you of any changes by
            posting the new Privacy Policy on this page.
          </Text>

          <Text style={styles.paragraph}>
            We will let you know via email and/or a prominent notice on our Service, prior to the
            change becoming effective and update "effective date" at the top of this Privacy Policy.
          </Text>

          <Text style={styles.paragraph}>
            You are advised to review this Privacy Policy periodically for any changes. Changes to
            this Privacy Policy are effective when they are posted on this page.
          </Text>

          <Text style={styles.paragraph}>
            21. <Text style={styles.bold}>Refund Policy</Text>
          </Text>

          <Text style={styles.paragraph}>
            At Hotel Virat, we strive to provide the best service to our guests. However, we
            understand that sometimes issues may arise that are beyond our control.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Refund Eligibility:</Text>
          </Text>

          <Text style={styles.paragraph}>
            If you experience any inconvenience during your stay or booking that warrants a refund,
            we will review your case on an individual basis. Refunds may be approved in cases of:
          </Text>

          <Text style={styles.paragraph}>0.1. Service disruptions beyond our control</Text>

          <Text style={styles.paragraph}>0.2. Booking errors or system malfunctions</Text>

          <Text style={styles.paragraph}>0.3. Unavailability of confirmed reservations</Text>

          <Text style={styles.paragraph}>
            0.4. Other legitimate concerns that significantly impact your experience
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Refund Processing:</Text>
          </Text>

          <Text style={styles.paragraph}>
            For approved refunds, the amount will be credited to the source account (original
            payment method) within 5-7 business days from the date of approval. Please note that the
            actual time for the funds to reflect in your account may vary depending on your bank or
            payment provider's processing time.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>How to Request a Refund:</Text>
          </Text>

          <Text style={styles.paragraph}>
            To request a refund, please contact us at{' '}
            <Text style={styles.bold}>infohotelvirat@gmail.com</Text> with your booking details and
            a description of the issue. Our team will review your request and respond within 2-3
            business days.
          </Text>

          <Text style={styles.paragraph}>
            22. <Text style={styles.bold}>Contact Us</Text>
          </Text> 
          <Text style={styles.paragraph}>
            23. <Text style={styles.bold}>Shipping Policy</Text>
          </Text>

          <Text style={styles.paragraph}>
            At Hotel Virat, we are committed to providing fast and reliable delivery services to our customers.
          </Text>

          <Text style={styles.paragraph}>
            <Text style={styles.bold}>Delivery Timeframe:</Text>
          </Text>

          <Text style={styles.paragraph}>
            All orders placed through our service will be delivered within <Text style={styles.bold}>2-4 hours</Text> from the time of order confirmation, subject to availability and delivery location.
          </Text>

         

       

  

          
          <Text style={styles.paragraph}>
            24. <Text style={styles.bold}>Contact Us</Text>
          </Text>

          <Text style={styles.paragraph}>
            If you have any questions about this Privacy Policy, our Refund Policy, or our Shipping Policy, please contact
            us by email: <Text style={styles.bold}>infohotelvirat@gmail.com</Text>.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  backButton: {
    paddingVertical: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '500',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 32,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mainTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  paragraph: {
    fontSize: 14,
    lineHeight: 22,
    color: '#333',
    marginBottom: 12,
  },
  bold: {
    fontWeight: 'bold',
  },
});

export default PrivacyPolicy;